##installation of Monitoring Tools (sFlow-RT) and all the dependencies

---
- hosts: sflow_machine
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Get home directory of the user
      shell: "getent passwd {{ ansible_user }} | cut -d: -f6"
      register: user_home

    - name: Print home directory
      debug:
        var: user_home.stdout



    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - perl
        - make
        - terminator
        - openjdk-11-jdk
        - openjdk-17-jre-headless
        - git
        - git-review
        - zip
        - curl
        - unzip
        - bzip2
        - python3-dev
        - python3-setuptools
        - python3-pip
        - xterm
        - default-jdk
        - python3
        - snapd

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
        - lsb-release

    - name: Create directory for Docker keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'



    - name: Debug before adding GPG key
      debug:
        msg: "Before adding GPG key"


    - name: Add Docker GPG key to apt keyring
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -


    - name: Debug after adding GPG key
      debug:
        msg: "After adding GPG key"


    - name: Add Docker repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes

    - name: Update package lists again
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io


    - name: Add Java environment variables
      lineinfile:
        dest: /etc/environment
        line: |
          JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          JRE_HOME=/usr/lib/jvm/java-17-openjdk-amd64


    - name: Gather package facts
      package_facts:
        manager: apt




    - name: Install Python
      apt:
        name: "{{ 'python' if 'python' in ansible_facts.packages else 'python-is-python3' }}"
        state: present


    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
      when: ansible_distribution_major_version|int == 16


    - name: Update Package Manager
      command: sudo apt update



    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present


    - name: Upgrade pip for Python 3
      pip:
        name: pip
        state: latest
        executable: pip3


    - name: Ensure Docker service is running
      service:
        name: docker
        state: started



    - name: Install Portainer
      shell: |
        sudo docker rm -f portainer

        sudo docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v portainer_data:/data \
        portainer/portainer-ce:2.9.3


    - name: Create a data directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ user_home.stdout }}/data"
   

    - name: Create prometheus.yml file
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: "{{ user_home.stdout }}/prometheus.yml"


    - name: Install prometheus as a container
      shell: |
        sudo docker rm -f prometheus-sflow
        sudo docker run -d --user root --name prometheus-sflow --rm -v {{ user_home.stdout }}/data:/prometheus -v {{ user_home.stdout }}/prometheus.yml:/etc/prometheus/prometheus.yml -p 9090:9090 prom/prometheus


    - name: Install grafana as a container
      shell: |
        sudo docker rm -f grafana
        sudo docker run -d -p 3000:3000 --name=grafana grafana/grafana-oss