[onos_machine]
sdn-controller ansible_host=129.114.24.214 ansible_user=cc internal_ip=10.56.0.148 sflow_iface=ens3

[mininet_machine]
sdn-controller ansible_host=129.114.24.214 ansible_user=cc internal_ip=10.56.0.148 sflow_iface=ens3

[sflow_machine]
sdn-controller ansible_host=129.114.24.214 ansible_user=cc internal_ip=10.56.0.148 sflow_iface=ens3

[masters]
master ansible_host=129.114.27.112 ansible_user=cc internal_ip=10.56.1.209 tap0_ip=192.168.100.100/24

[workers]
worker1 ansible_host=129.114.26.244 ansible_user=cc internal_ip=10.56.1.101 tap0_ip=192.168.100.101/24
worker2 ansible_host=129.114.25.168 ansible_user=cc internal_ip=10.56.3.6 tap0_ip=192.168.100.102/24

[llm_machine]
llm-server ansible_host=129.114.26.41 ansible_user=cc internal_ip=10.56.2.204

[kubernetes:children]
masters
workers
